### PR TITLE
egress/dns-proxy: switch to haproxy 2.x

### PR DESCRIPTION
**Pull request by frobware**
Move to haproxy 2.x which is packaged here:

https://pkgs.devel.redhat.com/cgit/rpms/haproxy/log/?h=rhaos-4.4-rhel-7

### CODE REVIEW

**Comment by frobware** [comment]
Corresponding router change: https://github.com/openshift/router/pull/71

**Comment by frobware** [comment]
Running e2e-aws again (Fri 13 Dec 18:30:48 GMT 2019)

/test e2e-aws

**Comment by frobware** [comment]
Clean CI run; starting another @ Mon 16 Dec 2019 09:45:53 AM GMT

/test e2e-aws

**Comment by frobware** [comment]
failure: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_images/14/pull-ci-openshift-images-master-e2e-aws/17

/test-e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_images/14/pull-ci-openshift-images-master-e2e-aws/18

/test e2e-aws

**Comment by ironcladlou** [comment]
@smarterclayton @knobunc can we get this tagged?

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_images/14/pull-ci-openshift-images-master-e2e-aws/19

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_images/14/pull-ci-openshift-images-master-e2e-aws/20

/test e2e-aws

**Comment by frobware** [comment]
Cluster failed to start:

```console
2019/12/17 09:23:39 Waiting for template instance to be ready
2019/12/17 09:23:41 Running pod e2e-aws
Installing from release registry.svc.ci.openshift.org/ci-op-647jk3k4/release@sha256:cd21e29570d8778c9e357c18debd0ffdcae9cd4ddf4e00b077bab9ed1e83e2e2
level=info msg="Credentials loaded from the \"default\" profile in file \"/etc/openshift-installer/.awscred\""
level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Master Machines\": failed to generate asset \"Platform Credentials Check\": validate AWS credentials: mint credentials check: error simulating policy: Throttling: Rate exceeded\n\tstatus code: 400, request id: a09093d8-b5af-4834-94a4-ee43de562470"
2019/12/17 09:23:52 Container setup in pod e2e-aws failed, exit code 1, reason Error
Another process exited
```

/test e2e-aws

**Comment by frobware** [comment]
failures (9): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_images/14/pull-ci-openshift-images-master-e2e-aws/22

/test e2e-aws

**Comment by RiRa12621** [comment]
Great to see that happening

**Comment by smarterclayton** [comment]
We're broken because haproxy18 was removed, this has passed, I'm going to force merge.

**Pull request merged**
