### PR TITLE
NE-1304: container builds: switch to haproxy26 package

### PR DESCRIPTION
**Pull request by frobware**
https://issues.redhat.com/browse/NE-1304

### CODE REVIEW

**Comment by dgoodwin** [comment]
Needs lgtm and approved before we can get this merged.

**Comment by frobware** [comment]
- haproxy 2.6.13 bump now pushed: https://pkgs.devel.redhat.com/cgit/rpms/haproxy/commit/?h=rhaos-4.14-rhel-8&id=f764a5f6dda453173d8e41b5fffda7e4fac9576a
- RPM brew build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=53070151

Waiting for 2.6.13-1 RPM to turn up in https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.14/stream/el8/latest/x86_64/os/Packages/

**Comment by frobware** [comment]
/hold

Held for the same reason as detailed in https://github.com/openshift/router/pull/487#issuecomment-1576852856.

**Comment by ShudiLi** [comment]
From QE side, tested it with 4.14.0-0.ci.test-2023-06-06-030700-ci-ln-py51yx2-latest

`
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-0.ci.test-2023-06-06-030700-ci-ln-py51yx2-latest   True        False         101m    Cluster version is 4.14.0-0.ci.test-2023-06-06-030700-ci-ln-py51yx2-latest
% 

2.
% oc -n openshift-ingress get pods
NAME                             READY   STATUS    RESTARTS   AGE
router-default-98d6f87b5-2cjxj   1/1     Running   0          124m
router-default-98d6f87b5-ltcvf   1/1     Running   0          124m
% oc -n openshift-ingress rsh router-default-98d6f87b5-2cjxj
sh-4.4$ 

3.
sh-4.4$ haproxy -v
HAProxy version 2.6.13-234aa6d 2023/05/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.13.html
Running on: Linux 5.14.0-284.16.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 18 19:03:13 EDT 2023 x86_64
sh-4.4$ rpm -qa | grep haproxy
haproxy26-2.6.13-1.rhaos4.14.el8.x86_64
sh-4.4$ 

`

/label qe-approved
thanks

**Comment by frobware** [comment]
/hold cancel

haproxy-2.6.13-1 RPM now available.

**Pull request merged**
