### PR TITLE
[release-4.14] OCPBUGS-30414: update unit tests in egress/dns-proxy

### PR DESCRIPTION
**Pull request by lihongan**
this is manual cherry-pick https://github.com/openshift/images/pull/165

to replace https://github.com/openshift/images/pull/167

### CODE REVIEW

**Comment by frobware** [comment]
openshit/release PR for 4.14 is PR https://github.com/openshift/release/pull/51749.

**Comment by lihongan** [comment]
@jupierce @bparees could you please help take a look? thanks

**Comment by alebedev87** [comment]
/approve

No rights or a miss?

**Comment by frobware** [comment]
@jupierce - PTAL if you can.

**Comment by Miciah** [comment]
@sdodson, are you able to approve this PR?   Do we need to backport #170 (and possibly #169)?

**Comment by Miciah** [comment]
https://github.com/openshift/release/pull/51749 will also need to be approved to resolve OCPBUGS-30414.

**Pull request merged**
