### PR TITLE
OKD-219: add util-linux to base image

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by LorbusChris** [comment]
/close
in favor of https://github.com/openshift/egress-router-cni/pull/82 (we might want to revisit this again though)

**Comment by ausil** [comment]
/retitle OKD-219: add util-linux to base image

**Comment by jupierce** [comment]
/override ci/prow/e2e-aws
/override ci/prow/e2e-aws-upgrade
/override ci/prow/e2e-metal-ipi-ovn-ipv6
These packages already exist in RHEL base images, so this is a no-op. This change only makes CentOS base images similar to RHEL base images.

**Pull request merged**
